#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAnimationsDemo.Resource", IsApplication=true)]

namespace XamarinAnimationsDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int card_flip_left_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int card_flip_left_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int card_flip_right_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int card_flip_right_out = 2130968579;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_info = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_new = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_photo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_launcher = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_list_remove = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int image1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int image2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int thumb1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int thumb2 = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int action_add_item = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int action_flip = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int action_next = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int action_previous = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int action_toggle = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int container = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int content = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int delete_button = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int expanded_image = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int loading_spinner = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int pager = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int thumb_button_1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int thumb_button_2 = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int card_flip_time_full = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int card_flip_time_half = 2131099649;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_card_flip = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_crossfade = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_layout_changes = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_screen_slide = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_zoom = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int excerpt_content = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int fragment_card_back = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int fragment_card_front = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int fragment_screen_slide_page = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int list_item_example = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int activity_crossfade = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int activity_layout_changes = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int activity_screen_slide = 2131296258;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070008
			public const int action_add_item = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int action_finish = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int action_info = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int action_next = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int action_photo = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int action_previous = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int action_remove_item = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int action_toggle = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070015
			public const int card_back_description = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int card_back_title = 2131165204;
			
			// aapt resource value: 0x7f070011
			public const int description_image_1 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int description_image_2 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int description_zoom_touch_close = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int lorem_ipsum = 2131165206;
			
			// aapt resource value: 0x7f07000f
			public const int message_empty_layout_changes = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int message_zoom_touch_expand = 2131165200;
			
			// aapt resource value: 0x7f070002
			public const int title_card_flip = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int title_crossfade = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int title_layout_changes = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int title_screen_slide = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int title_template_step = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int title_zoom = 2131165188;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int DarkActionBar = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int DarkTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
