//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoDroid.Calendar
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040003
			public const int cell_height = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int cell_margin_left = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int cell_margin_top = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int cell_text_size = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int cell_width = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int week_left_margin = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int week_top_margin = 2130968576;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar_week = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int typeb_calendar_today = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int hint = 2131099649;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int about = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int about_summary = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int app_name = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int hint = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int pick = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int pick_summary = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int show = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int show_summary = 2131034116;
			
			private String()
			{
			}
		}
	}
}
