#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("custom_item.Resource", IsApplication=true)]

namespace custom_item
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int custom_progress = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fondo_degradado = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int img1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int img10 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int img2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int img3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int img4 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int img5 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int img6 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int img7 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int img8 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int img9 = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int imgPortada_item = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int lwLibros = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int pbProgreso = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int txtAutor = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int txtNombre = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int txtPaginas = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int custom_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
